Предметы и несколько имен! Закончилось время!
SBT-community/Starbound_RU pull request #106
Opened 2019-06-29 21:05 UTC by Kolan4ik65488

2019-06-30 14:49 UTC, xomachine reviewed
Пожалуйста, не используйте гугл-переводчик вслепую. Некоторые предложения просто невозможно понять. Хотябы вычитывайте и перефразируйте их, как только сами сможете понять смысл.

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/unsorted/arrester/arrester.activeitem.json
> +      "Rus": "Используется для ареста и выведения из строя уполномоченных наградных целей."
не думаю, что преступникам дали какие-то полномочия

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/unsorted/laserminer/laserminer.activeitem.json
> +      "Rus": "\nОдноразовый инструмент для горной промышленности, который сверлит с сфокусированным микроволновым лучом."
Лишний перенос строки

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/unsorted/miningdrone/miningdrone.activeitem.json
> +      "Rus": "Одноразовая механическая сова, которая будет лететь в одном направлении и рыть туннель при броске."
... если её бросить

мне кажется так будет понятнее

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/unsorted/papernote/papernote.activeitem.json
> +      "Rus": "Рукописная заметка.Я должен увидеть что говорят!"
... о чём она

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/unsorted/stunmine/stunmine.activeitem.json
> +      "Rus": "Этот инерционный ингибитор, запускаемый дистанционно, удерживает субъектов на короткое время в заблокированном месте."
Так, тут гуглтранслейт не прокатит!

Не место заблокировано, а субъекты. Да и не заблокированы, а пригвозжены к месту...

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/active/weapons/ranged/unrand/neolaserlauncher/neolaserlauncher.activeitem.json
> +      "Rus": "Мощная протонная пушка, построенная, чтобы нести тяжелое правосудие."
Тогда уж нести правосудие в тяжёлых случаях

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/armors/decorative/hats/groucho/groucho.head.json
> +      "Rus": "Оригинальная маскировка. Будь лучшим."
Всё ещё лучшая [маскировка]

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/armors/other/captainnoble/captainnoble.head.json
> +      "Rus": "Голова капитана Нобла"
Капитан имеет фамилию Нобель (см. Глоссарий)

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/armors/other/captainnoble/captainnoble.head.json
> +      "Rus": "Для капитана Нобла - не для ношения на себе!"
Фамилия капитана

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/armors/other/invisible/invisible.back.json
> +      "Rus": "Невидимая спина"
Не спина невидимая, а плащ

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/armors/other/peacekeeper/peacekeeper.head.json
> +      "Rus": "Униформу шлем Миротворца - носили Миротворцы в солнечные дни."
Попробуйте прочитать это вслух. Ничего странного не замечаете?

Может всё же нужно перефразировать, а не верить гугл-переводчику?

2019-06-30 14:49 UTC, xomachine commented on translations/texts/items/throwables/stungrenade.thrownitem.json
> +      "Rus": "Граната, которая создает локализованное нанополе, чтобы заморозить противников на своем пути.\n"
которое замораживает

и лишний перенос строки

2019-06-30 14:49 UTC, xomachine commented on translations/texts/objects.json
> +      "Rus": "Потрескивающий факел.\n"
лишний перенос строки

2019-06-30 14:49 UTC, xomachine commented on translations/texts/objects.json
> +      "Rus": "Поднятый факел обеспечивает свет для обширной области."
Никто его не поднимал, он просто закреплён на длинной палке

2019-06-30 14:49 UTC, xomachine commented on translations/texts/objects.json
> +      "Rus": "Напрочь мерцающий факел."
Нет

2019-06-30 14:49 UTC, xomachine commented on translations/texts/objects.json
> +      "Rus": "Высокий факел, пламя мерцает."
_его_ пламя мерцает

2019-06-30 14:49 UTC, xomachine commented on translations/texts/stats/effects/neon/neon.statuseffect.json
> +      "Rus": "Неон"
Не уверен, что здесь уместна большая буква

2019-06-30 14:49 UTC, xomachine commented on translations/texts/system_objects.config.json
> +      "Rus": "Большая космическая станция имеет множество удобств, используемых в качестве центра для миротворцев."
Каких ещё удобств? Как они используются? Что за бред?

2019-06-30 18:56 UTC, Kolan4ik65488 commented
Проверь теперь я чуть под исправил хз верно или нет ))

2019-06-30 18:58 UTC, Kolan4ik65488 commented
Поздно было чуть накосячил даже не вчитывался ))

2019-07-01 17:45 UTC, xomachine requested changes
Ещё раз попрошу, проводите вычитку переведённого текста, иначе этот запрос так и не будет принят и погрязнет в бесконечных правках.

Представьте себе, что Вы читаете хорошую книгу или смотрите качественно переведённый фильм. Будут ли в этой книге (или в фильме) фразы, подобные тем, что получились у Вас?

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Похоже, ваша цель очень близко.^orange;Задержать цель^reset;,партнер!"
Тут капитан Нобель общается с нами в приказном тоне

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Похоже, ты приближаешься к цели, партнер.^orange;Исследуйте^reset; назначенную область!"
... а тут переходит на Вы...

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Мы засекли ^orange;целевую сигнатуру^reset;!Ваш ^green;компас^reset; покажет вам направление - следуйте за ним, партнер!\n"
... и добавляет лишние переносы строки...
... и забывает пробелы...
... похоже у него начинает двоиться в глазах, поскольку второе "вы" с маленькой буквы...

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Ваша цель может быть где угодно на этой планете, даже под землей! ^green;Исследуйте^reset; планету, пока мы не подберем ^orange;сигнатуру цели^reset;, партнер!\n"
... на этом этапе я начинаю подозревать у капитана шизофрению, читая перевод...

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/missions.radiomessages.json
> +      "Rus": "Я думаю, что это так, дорогой. Я надеюсь, что вы готовы .."
Эта фраза принадлежит Эстер Брайт, а у неё своеобразная манера обращения, которая описана в Глоссарии и которую обязательно надо передавать единообразно

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/missions.radiomessages.json
> +      "Rus": "Все мое удовольствие, дорогой!"
Нет. https://forum.wordreference.com/threads/the-pleasure-is-mine.35667/

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Надеюсь, тебе понравится новая станция, партнер! У нас даже есть^orange;магазин снабжения Миротворцев^white;сейчас!"
Миротворцевсейчас

хотя на самом деле теперь

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Новая станция не так уж плоха, если я сам так говорю! Мы развиваемся, партнер!"
> если я сам так говорю

не обязательно знать английский, чтобы понять, что с этой фразой что-то не так

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Мы наконец-то добились успеха, партнер! Миротворцы хорошо и \"действительно вернулись, и выглядят\" лучше, чем когда-либо!\n"
лишний перенос строки

кавычки тут тоже не к месту, в оригинале были апострофы чтобы передать ковбойскую манеру речи новакидов с проглатыванием последних букв
old -> ol'
looking -> lookin'
and -> an'

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Добро пожаловать в наше прекрасное новое место, партнер! Почему бы не проверить наш^orange;магазин мебели Миротворцев^white;?"
нашмагазин

2019-07-01 17:45 UTC, xomachine commented on translations/texts/system_objects.config.json
> +      "Rus": "Большая космическая станция имеет множество обьектов, которые используются в центре для Миротворцев."
всё ещё нет

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/missions.radiomessages.json
> +      "Rus": "Мне не нравится внешний вид всего этого, напарник."
как это выглядит

2019-07-01 17:45 UTC, xomachine commented on translations/texts/items/armors/other/peacekeeper/peacekeeper.head.json
> +      "Rus": "Шлем униформа Миротворца - носили Миротворцы в солнечные дни."
всё ещё нет

2019-07-01 17:45 UTC, xomachine commented on translations/texts/items/active/unsorted/arrester/arrester.activeitem.json
> +      "Rus": "Используется для ареста и выведения из строя наградных целей."
что такое наградные цели?

2019-07-01 17:45 UTC, xomachine commented on translations/texts/interface/scripted/bountyboard/bountyboardgui.config.json
> +      "Rus": "БОЛЬШОЕ ЗНАЧЕНИЕ"
скорее значимость

2019-07-01 17:45 UTC, xomachine commented on translations/texts/objects.json
> +      "Rus": "Закреплённый деревяный факел"
точка потеряна

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Мы знаем, что цель была здесь недавно.^orange;Ищите^reset; подсказки.Не знаете с чего начать? Оглянись, партнер!"
капитан должен обращаться к игроку в одинаковой манере. ВСЕГДА!

2019-07-01 17:45 UTC, xomachine commented on translations/texts/radiomessages/missions.radiomessages.json
> +      "Rus": "Впечатленный. Несмотря на их поступки, эти отвратительные культисты, по крайней мере, знают, как сохранить тайную комнату в чистоте! Ха ха!"
Эта фраза, очевидно, принадлежит Барону. Барон - глич. Как мы переводим эмоции гличей?

2019-07-01 17:45 UTC, xomachine commented on translations/texts/species/namegen.config.json
> +      "Rus": "бакон"
я бы не спешил с переводом этих штук. я не видел их в игре, возможно если их перевести так, в игре они превратятся в какую-то дичь

2019-07-02 17:53 UTC, xomachine reviewed
Чтож, на этот раз замечаний меньше, однако всё ещё нужно приложить больше усилий.

2019-07-02 17:53 UTC, xomachine commented on translations/texts/items/armors/other/peacekeeper/peacekeeper.head.json
> +      "Rus": "Головной убор Миротворца - носили Миротворцы в солнечные дни."
Вы серьёзно не видите в чём проблема данного перевода?

Тогда объясню. Вы в жизни говорите так: "Головной убор Миротворца - носили Миротворцы в солнечные дни."?
Я лично не слышал предложений с такой конструкцией. Кроме того, worn - это passive voice в (предположительно) present simple с опущеным глаголом, а вовсе не past simple

2019-07-02 17:53 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Похоже, твоя цель очень близко.^orange;Задержать цель^reset;,партнер!"
Вы серьёзно считаете нормальной манеру общения, когда не с того, не с чего человек начинает отдавать другому приказы как собаке?

2019-07-02 17:53 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Похоже, ты приближаешся к цели, партнер.^orange;Исследуй^reset; назначенную область!"
Пробела нет между точкой и "Исследуй". И зря Вы исправили слово приближаешься, оно было правильно написано

2019-07-02 17:53 UTC, xomachine commented on translations/texts/radiomessages/bounty.radiomessages.json
> +      "Rus": "Мы знаем, что цель была здесь недавно.^orange;Ищи^reset; подсказки.Не знаеш с чего начать? Оглянись, партнер!"
мягкий знак потерян, как и пробел между точкой и "Ищи"

2019-07-02 17:53 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Надеюсь, тебе понравится новая станция, партнер! У нас даже есть ^orange;магазин снабжения Миротворцев^white; теперь!"
У нас теперь даже есть

2019-07-02 17:53 UTC, xomachine commented on translations/texts/radiomessages/tutorial.radiomessages.json
> +      "Rus": "Мы наконец-то добились успеха, партнер! Миротворцы хороши и действительно вернулись, и выглядят лучше, чем когда-либо!"
Позвольте описать последовательность действий как я дошёл до правильного перевода. Возможно она Вам поможет.

* Мне всё ещё не нравится, как звучит это предложение.
* Даже более того, мне даже не нравится, как оно звучит, если бы я переводил его сам.
* Странное сочетание well and truly back не даёт мне покоя, я подозреваю идиому.
* Лезу в гугл и вбиваю well and truly back, нахожу много таких сочетаний - это точно идиома.
* Повторяю запрос добавив idiom в конец и получаю:
https://dictionary.cambridge.org/dictionary/english/well-and-truly

2019-07-02 17:53 UTC, xomachine commented on translations/texts/species/namegen.config.json
> -[
Этот файл не следовало удалять. Но я сам это исправлю, когда буду мержить.

2019-07-02 17:53 UTC, xomachine commented on translations/texts/system_objects.config.json
> +      "Rus": "Большая космическая станция имеет множество обородования, которое используется в центре для Миротворцев."
used относится к station, а не к facilities.
ну и as  - как, а не в
facilities скорее отсеки, применительно к станции, а не оборудование

2019-07-03 16:03 UTC, xomachine commented
Сожалею, но Вас опередили с большинством переводов. Поэтому я закрываю этот запрос

2019-07-03 16:03 UTC, closed without merging