Web interface
SBT-community/Starbound_RU pull request #26
Opened 2017-01-25 20:39 UTC by konerini

Объекты флоран

2017-01-25 21:06 UTC, xomachine requested changes
В основном всё отлично, единственное, есть пара моментов которые нужно исправить. Пересоздавать запрос при этом необязательно. Все изменения из твоей копии я увижу.

2017-01-25 21:06 UTC, xomachine commented on translations/texts/glitchEmotes.json
> +      "Rus": "Подавлено."
Слишком много подавленностей у гличей. Думаю, не стоит добавлять в глоссарий третье слово, которое переводится так же. Предыдущие 2 - devastated и Dispondent

2017-01-25 21:06 UTC, xomachine commented on translations/texts/objects/floran/floranbed/floranbed.object.json
> +      "Rus": "Флоран ссспит сссреди костей и меха. Запах охоты делать флоран видеть хорошие сссны."
не надо тут делать кальку с английского. Флораны неграмотны, но при этом они не должны оставлять артефактов перевода. лучше будет "Запах охоты позволять флоран видеть хорошие сссны."

2017-01-25 21:06 UTC, xomachine commented on translations/texts/objects/floran/floranbonedisplay2/floranbonedisplay2.object.json
> +      "Rus": "Высеченный на этой кости текст рассказывает историю одной охоты, в ходе которой был убит флоран."
Немного придираюсь, но всё же, тут можно было немного ближе к тексту. 

> ... историю одной охоты. Похоже в ней был убит флоран.
Хотя  выглядит немного косноязычно, так что можно оставить как у тебя.

2017-01-25 23:23 UTC, konerini commented on translations/texts/objects/floran/floranbed/floranbed.object.json
> +      "Rus": "Флоран ссспит сссреди костей и меха. Запах охоты делать флоран видеть хорошие сссны."
Справедливо. Ок.

2017-01-26 00:00 UTC, xomachine approved these changes

2017-01-26 00:03 UTC, merged