Хочу внести изменения в ваш перевод
SBT-community/Starbound_RU pull request #29
Opened 2017-02-16 10:01 UTC by AlexMoroz43

2017-02-16 15:06 UTC, xomachine requested changes
Неплохая работа, хотя есть несколько небольших недочётов. Буду ждать исправлений.

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/avian/avianbench1/avianbench1.object.json
> +      "Rus": "Очаровательная скамейка, думаю её создателю не хватает мастерства."
Пропущено "хотя"

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/avian/ashjar3/ashjar3.object.json
> +      "Rus": "Эта банка выглядит очень знакомой."
Честно говоря, не уверен, что это именно банка.  Больше напоминает [вазу](http://starbounder.org/Familiar_Jar). Хотя, вопрос спорный, неплохо бы услышать мнение других учасников.

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/biome/frozen/shared_.object.json
> +      "Rus": "Кусочек льда."
Так всё-таки, это кусочек или большой осколок?

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/biome/frozen/shared_.object.json
> +      "Rus": "Большой осколок льда. Холод до самого его ядра."
Нужно перефразировать. У ледяного осколка нет ядра. Возможно имелось ввиду "Насквозь холодный" или что-то подобное.

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/biome/ocean/shared_seashell/shared_seashell.json
> +      "Rus": "Морская ракушка разбита! Что же внутри?"
суффикс able подразумевает _возможность_ разбить, на не состояние разбитости. Хотя конечно всё, что smashable скоро будет smashed, особенно в случае флоран и новакидов.

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/biome/ocean/shared_seashell/shared_seashell.json
> +      "Rus": "Кажется позором сломать ракушку."
Нужно перефразировать, а то рунглиш какой-то получается. В обычной речи так не говорят.

2017-02-16 15:06 UTC, xomachine commented on translations/texts/objects/biome/ocean/shared_seashell/shared_seashell.json
> +      "Rus": "Морские ракушки - настоящий клад природы."
может всё-таки сокровища?

2017-02-16 15:41 UTC, Woit commented on translations/texts/objects/avian/ashjar3/ashjar3.object.json
> +      "Rus": "Эй это похоже на..."
После "Эй" запятая

2017-02-16 15:42 UTC, Woit commented on translations/texts/objects/avian/ashjar3/ashjar3.object.json
> +      "Rus": "Я никогда не видел подобное существо прежде."
В русском практически всегда слово "прежде" употребялется перед глаголом действия. Т.е. "я никогда прежде не видел подобных существ" звучит более нативно

2017-02-16 15:46 UTC, Woit commented on translations/texts/objects/glitch/burlapsack/burlapsack.object.json
> +      "Rus": "Колллючий волоконный мешшшок."
обычно у флоран в речи дублируются только шипящие согласные

2017-02-16 16:07 UTC, Woit commented
@AlexMoroz43 пошли письмо с любым текстом на mitrofanovegor@ya.ru, я тебя добавлю в наш уютный чатик )

2017-02-16 16:10 UTC, xomachine commented on translations/texts/objects/avian/avianbench1/avianbench1.object.json
> +      "Rus": "Очаровательная скамейка, хотя думаю её создателю не хватает мастерства."
Про _хотя_ я, конечно, сказал, но вот _думаю_ тут немножко от себя добавлено. Теперь, как мне кажется, не хватает запятых. Я не слишком силён в орфографии, но, вроде, тут получилось два вводных слова.

2017-02-16 16:15 UTC, xomachine commented on translations/texts/objects/glitch/burlapsack/burlapsack.object.json
> +      "Rus": "Колллючий волоконный мешшшок."
кстати, да, не заметил. @AlexMoroz43 если вдруг не видел на сайте, вот [ссылка на глоссарий](https://docs.google.com/spreadsheets/d/11wsdVB_vysNa-GrdEjqbt2yOJivNBQZkg_yX0A_hvso), где описаны основные правила перевода реплик флоран.

2017-02-16 16:40 UTC, AlexMoroz43 commented
А после исправления что нужно делать?

2017-02-16 16:43 UTC, xomachine commented
Нет, запрос посмотрят другие учасники, и мы его примем.

2017-02-16 16:44 UTC, xomachine approved these changes

2017-02-16 23:45 UTC, xomachine commented on translations/texts/objects/biome/bioluminescentcave/bioshroom/bioshroom1.object.json
> +      "Rus": "Они помогают Флоран видеть в темноте"
У нас Флораны склоняются

2017-02-17 08:34 UTC, Kruptixx commented on translations/texts/objects/avian/avianbench1/avianbench1.object.json
> +      "Rus": "Это выглядит сделанным вручную. Очень мило."
"**Это выглядит сделанным вручную**" - советую заменить на что-нибудь отдаленное от дословного перевода.

2017-02-17 08:47 UTC, Kruptixx commented on translations/texts/objects/biome/frozen/shared_.object.json
> +      "Rus": "Осколок льда. Отличное орудие убийства."
"орудие **_для_** убийства"

2017-02-17 08:50 UTC, Kruptixx commented on translations/texts/objects/biome/ocean/shared_seashell/shared_seashell.json
> +      "Rus": "Морские ракушки - настоящий клад природы."
**_богатство_**, думаю, тоже подойдет.

2017-02-17 08:54 UTC, Kruptixx commented on translations/texts/objects/avian/ashjar3/ashjar3.object.json
> +      "Rus": "Эта банка выглядит очень знакомой."
Jar часто используется в значении "сосуд". В данном случае соглашусь с xomachine, лучше называть данный предмет ваза либо кувшин.

2017-02-17 09:09 UTC, xomachine commented on translations/texts/objects/biome/bioluminescentcave/bioshroom/shared_bioshroom.json
> +      "Rus": "Привет, небольшие светящиеся парни."
Это сказал новакид, с новакидами у нас всё сложно. Они ковбои, говорят по-деревенски и не любят длинных конструкций языка. Я бы перевёл как-нибудь так: "Здарова, светляки". Кстати, вопрос всем: может всех glowin' <кто-то там> в устах новакидов называть светляками?(всмысле в глосс добавить) Ну или еще какое короткое имя выдумать. В любом случае длинные "светящиеся" и "сияющие" не очень хорошо смотрится, не могу представить ковбоя, выговаривающиего эти слова.

2017-02-17 16:13 UTC, xomachine commented
Похоже @Xorras мы не дождёмся, потому замежду без его мнения.

2017-02-17 16:14 UTC, merged