Запрос на слияния!
SBT-community/Starbound_RU pull request #31
Opened 2017-03-23 16:47 UTC by Caroline434

Хочу чтобы вы посмотрели мои старания, и их оценили, я в переводах силен но не до конца, хочу помочь и чтобы вы помогли мне)) Постараюсь каждый день кидать перевод. Очень заинтересован в данной игре и переводом в целом. Спасибо за внимание

2017-03-23 17:44 UTC, xomachine requested changes
1. Жизненно необходимо проштудировать Глоссарий. В нём куча указаний как правильно перевести в том или ином случае.
2. Не нужно переводить "отсебятину". Если не знаешь как переводится - пропусти и переводи что знаешь.
3. Новакиды - отдельная песня. Лучше их пропускать до тех пор пока не почувствуешь в себе силу и не поймёшь как передать их говор.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/ancientbust/ancientbust.object.json
> +      "Rus": "Древний бюст, изображающий Создателя. Шар, которую он держит, источает свет."
>> Шар, которую

запятая действительно необходима, а вот рассогласование родов лишнее

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram1/hologram1.object.json
> +      "Rus": "На этой картине изображена какая-то таинственная, странная фигура."
Недостаточно точный перевод. Речь идет не просто о картине, а о старой картине. Перевод должен быть максимально близок к оригиналу

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/challengedoor/shared_door.object.json
> +      "Rus": "вызывающая дверь"
1. Названия объектов должны быть написаны с большой буквы
2. Вызывающая дверь это "Challenging Door", тут скорее дверь испытания, но надо еще глянуть на сам объект.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram4/hologram4.object.json
> +      "Rus": "Флоране лучшая раса! Надо держаться!"
Флоран иметь в виду другое, Флоран ссстукнуть остальных.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram4/hologram4.object.json
> +      "Rus": "Эй, смотри, наверху человек! Иди к нам!"
Эй, смотри, тот что на верху - человек! Люди вперед!
Feel the difference

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram4/hologram4.object.json
> +      "Rus": "Шесть рас, каждая из которых имеет что-то важное."
Нужно перефразировать. Насколько я помню, это буквальное описание голограммы из ковчега. Там расы действительно **держат** предметы.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram4/hologram4.object.json
> +      "Rus": "Шесть рас, держат «что-то». Почему моего вида тут нет?"
С новакидами надо осторожнее, слишком правильная речь для них. Лучше их пропускать, если не уверен как перевести с учётом их особенностей речи.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram2/hologram2.object.json
> +      "Rus": "Что-то похожее на кальмаров, выглядит ужасно..."
Новакиды требуют особого подхода. Лучше их пока оставить непереведёнными.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram2/hologram2.object.json
> +      "Rus": "Эта голограмма показаны щупальца, которые разрушили много планет."
Части предложения не согласованы.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram1/hologram1.object.json
> +      "Rus": "На этой голограмме изображена древняя фигура с планетами."
Тут имеет место предположение. Говорящий не уверен в том, что говорит.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram1/hologram1.object.json
> +      "Rus": "Голограмма - красивое и таинственное описание существа."
Речь идёт о конкретно этой голограмме, на что указывает артикль the. Надо перефразировать, а то из перевода получается, что речь идёт о голограммах вообще.

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/hologram1/hologram1.object.json
> +      "Rus": "Древние надписи могут быть неопределенными и таинственными..."
"love to be" ну никак не может быть переведено как "могут быть"

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/ancientmural/shared_ancientmural/shared_ancientmural.json
> +      "Rus": "Я видел это раньше? Я должен вспомнить."
Не должен он никому.
> Не, **должно быть** воображение разыгралось.

Для всяких словечек типа Naw есть отличный сайт http://www.urbandictionary.com

2017-03-23 17:44 UTC, xomachine commented on translations/texts/objects/ancient/ancientbust/ancientbust.object.json
> +      "Rus": "Как насчет этого. Я не могу поверить, что этот свет все еще работает."
Новакиды требуют особого подхода. Нужно передать их манеру речи. В глоссе есть указания. Если не получается или получается хрень - лучше высказывание пропустить.

2017-03-24 10:17 UTC, Kruptixx commented on translations/texts/objects/ancient/ancientbust/ancientbust.object.json
> +      "Rus": "Древний бюст, изображающий Создателя. Шар, которую он держит, источает свет."
"_Шар, которЫЙ..._" Хотя, в данном случае, как мне кажется, сфера лучше подойдет.

2017-03-24 10:27 UTC, Kruptixx commented on translations/texts/objects/ancient/ancientbust/ancientbust.object.json
> +      "Rus": "Похоже эта статуя изображает сильную, древнюю расу."
_Сильный_ и _древний_ - неоднородные определения. Между ними запятая не ставится.
В данном случае "_похоже_" является вводным словом. После него запятая обязательна.

2017-03-24 10:36 UTC, Kruptixx commented on translations/texts/objects/ancient/hologram1/hologram1.object.json
> +      "Rus": "Светящаяся картинка, человек помогает планетам."
_Glowing picture man_ - никак нельзя перевести как "светящаяся картинка". Эта фраза имеет значение "светящаяся картина/изображение/рисунок человека" (_picture_ стоит перевести исходя из внешнего вида объекта. Это можно посмотреть на вики).

2017-03-24 10:55 UTC, xomachine commented on translations/texts/objects/ancient/ancientbust/ancientbust.object.json
> +      "Rus": "Похоже эта статуя изображает сильную, древнюю расу."
Вообще, мне кажется тут лучше перевести powerful как "могучая".

2017-07-28 11:17 UTC, Xorras commented
Запрос изменений был оставлен без внимания

2017-07-28 11:17 UTC, closed without merging